print("                                CV")
print("Nume, prenume: Fedoseeva Alexandra")
print("Data si anul nasterii: 22.01.2004")
print("Adresa:-")
print("E-mail: Moon.beem4you@gmail.com")
print("Studii: gimnaziale la IPLT Mihai Eminescu")
print("Limba materna: romana")
print("Cunoasterea limbilor straine: engleza B2; franceza B1")
print("Interese: muzica, pictura,limbile straine, sport, turism")
print("alte aptitudini: 6 ani de studiu la Scoala de Arte si Pictura din mun. Balti")